apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  restartPolicy: Always
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-data
  - name: busybox-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - |
        count=1
        while true; do
          echo "<html><body><h1>Count: $count</h1></body></html>" > /shared-data/index.html
          count=$((count + 1))
          sleep 1
        done
    volumeMounts:
    - mountPath: /shared-data
      name: shared-data
  volumes:
  - name: shared-data
    emptyDir: {}

