apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: mynamespace  # Optional: specify your namespace here
  labels:
    app: nginx  # Added label her
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
