apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mynamespace  # Optional: specify your namespace here
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Optional: set a specific node port (e.g., 30007)
  type: NodePort
