apiVersion: v1
kind: Pod
metadata:
  name: simple-init-container-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo 'Init container is running...'; sleep 2;"]
  containers:
  - name: main-container
    image: busybox
    command: ["sh", "-c", "echo 'Main container is running!'; sleep 3600"]
