apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end  # Fixed typo here (from 'fornt-end' to 'front-end')
spec:
  containers:
  - name: nginx-container  # Fixed indentation here
    image: nginx
    ports:
    - containerPort: 80

