apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-dep
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: nginx:1.27.5   #1.28.0
        imagePullPolicy: Always
        name: hello-dep
        ports:
        - containerPort: 8080
